apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opa-dev
  namespace: opa-dev
spec:
  releaseName: opa-dev
  chart:
    spec:
      chart: ./iac/helm/opa-chart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: opa
  interval: 1m
  values:
    - ./iac/helm/values/dev/values.yaml

