apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app2
  namespace: opa
spec:
  releaseName: app2
  chart:
    spec:
      chart: ./demo-chart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: app2
  interval: 1m

